function [fitresult, gof] = createFit(tempi_tmp, uu_tmp)
%CREATEFIT(TEMPI_TMP,UU_TMP)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : tempi_tmp
%      Y Output: uu_tmp
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 11-Dec-2020 15:08:15


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( tempi_tmp, uu_tmp );

% Set up fittype and options.
ft = fittype( 'a*exp(-b*x) + c', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [-10 0.2 95];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'uu_tmp vs. tempi_tmp', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'tempi_tmp', 'Interpreter', 'none' );
ylabel( 'uu_tmp', 'Interpreter', 'none' );
grid on


